version: "3.3"

networks:
  welearn_network:
    driver: "bridge"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    networks:
      - "welearn_network"
    environment:
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_DATABASE=welearn"
    ports:
      - "3306:3306"
    restart: always