server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: "12MB"
      max-request-size: "12MB"
  datasource:
    url: "jdbc:h2:mem:testdb?stringtype=unspecified&useUnicode=true&characterEncoding=UTF-8"
    username: "sa"
    password: "password"
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    url: "jdbc:h2:mem:testdb?stringtype=unspecified&useUnicode=true&characterEncoding=UTF-8"
    username: "sa"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: "30"
        order_inserts: "true"
        order_updates: "true"
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.H2Dialect
